version: '3.8'

services:
  shopmdlserver:
    build: .
    container_name: shopmdlserver
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: npm run dev

volumes:
  node_modules: